<?php

/**
 * @file
 * Primary module hooks for Form Crud module.
 */


/**
 * Implements hook_theme().
 */
function form_crud_theme(): array
{
    $themes['tabla_listado'] = [
        'variables' => [
            'people_header' => '',
            'people_rows' => '',
            'form_data' => '',
            'type' => '',
            'id' => ''
        ],
    ];

    $themes['xform_crud'] = [
        'variables' => ['form_data' => '', 'type' => '', 'id' => ''],
    ];

    $themes['ver_detalle'] = [
        'variables' => ['form_data' => ''],
    ];

    return $themes;
}

/**
 * Implements hook_page_attachments().
 */
function form_crud_page_attachments(array &$attachments)
{
    $attachments['#attached']['library'][] = 'form_crud/form_crud_js_css';
    $attachments['#attached']['library'][] = 'bootstrap/slick_carousel_library';
}
