<?php

/**
 * @file
 * Primary module hooks for Drupal Entity Form module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function drupal_entity_form_theme(): array {
  return [
    'drupal_entity_form_people' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for people templates.
 *
 * Default template: drupal-entity-form-people.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the people information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_drupal_entity_form_people(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function drupal_entity_form_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish peoples.
      $storage = \Drupal::entityTypeManager()->getStorage('drupal_entity_form_people');
      $drupal_entity_form_people_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($drupal_entity_form_people_ids) as $drupal_entity_form_people) {
        $drupal_entity_form_people->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize peoples.
      $storage = \Drupal::entityTypeManager()->getStorage('drupal_entity_form_people');
      $drupal_entity_form_people_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($drupal_entity_form_people_ids) as $drupal_entity_form_people) {
        $drupal_entity_form_people->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function drupal_entity_form_user_predelete(UserInterface $account): void {
  // Delete peoples that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('drupal_entity_form_people');
  $drupal_entity_form_people_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($drupal_entity_form_people_ids)
  );
}
